---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cds-reload-lb-configuration-sa
  namespace: kube-system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cds-reload-lb-configuration-role
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["extensions", "apps"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cds-reload-lb-configuration-role-bind
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cds-reload-lb-configuration-role
subjects:
  - kind: ServiceAccount
    name: cds-reload-lb-configuration-sa
    namespace: kube-system
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: reload-lb-system-config
  namespace: kube-system
data:
  reload-lb-system-config: |+
    [default]
    haproxy.refresh.period = 300
    node.refresh.period = 30
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cds-reload-lb-configuration
  namespace: kube-system
spec:
  serviceName: reload-lb-svc
  replicas: 1
  selector:
    matchLabels:
      cds-app: cds-reload-lb-configuration
  template:
    metadata:
      labels:
        cds-app: cds-reload-lb-configuration
    spec:
      serviceAccountName: cds-reload-lb-configuration-sa
      containers:
        - env:
            - name: CDS_OVERSEA
              valueFrom:
                configMapKeyRef:
                  name: cds-properties
                  key: oversea
            - name: DEPLOY_TYPE
              valueFrom:
                configMapKeyRef:
                  name: cds-properties
                  key: deploy_type
            - name: CDS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: cck-secrets
                  key: access_key_id
            - name: CDS_ACCESS_KEY_SECRET
              valueFrom:
                secretKeyRef:
                  name: cck-secrets
                  key: access_key_secret
          image: capitalonline/cds-ha-configuration:v1.0
          name: cds-reload-lb-configuration
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /reload-lb/
              name: reload-lb-system-config
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Exists
        - effect: NoSchedule
          operator: Exists
          key: node-role.cck.net/infra
      restartPolicy: Always
      volumes:
        - configMap:
            defaultMode: 420
            name: reload-lb-system-config
          name: reload-lb-system-config
