apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: etcd-backup
  namespace: kube-system
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup
            image: registry-bj.capitalonline.net/cck/etcd:3.4.3-0
            env:
            - name: ETCDCTL_API
              value: "3"
            command: ["/bin/sh", "-c"]
            args: ["etcdctl --endpoints=https://127.0.0.1:2379 --cacert=/cck-kubernetes/ca.crt --cert=/cck-kubernetes/healthcheck-client.crt --key=/cck-kubernetes/healthcheck-client.key endpoint status --cluster | cut -f 1,5 -d ',' | grep true| cut -f1 -d ',' | xargs -I {} etcdctl --endpoints={} --cacert=/cck-kubernetes/ca.crt --cert=/cck-kubernetes/healthcheck-client.crt --key=/cck-kubernetes/healthcheck-client.key snapshot save /backup/etcd-snapshot-$(date +%Y-%m-%d_%H:%M:%S_%Z).db"]
            volumeMounts:
            - mountPath: /cck-kubernetes
              name: cck-kubernetes
              readOnly: true
            - mountPath: /backup
              name: backup
          restartPolicy: OnFailure
          nodeSelector:
            node-role.kubernetes.io/master: ""
            node-role.kubernetes.io/infra: ""
          tolerations:
          - key: "node-role.kubernetes.io/master"
            effect: "NoSchedule"
          - effect: NoSchedule
            key: node-role.cck.net/infra
          hostNetwork: true
          volumes:
          - name: cck-kubernetes
            hostPath:
              path: /etc/kubernetes/pki/etcd
              type: DirectoryOrCreate
          - name: backup
            persistentVolumeClaim:
              claimName: etcd-backup-pvc
              
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: etcd-backup-pvc
  namespace: kube-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi



