apiVersion: kubeadm.k8s.io/v1beta1
kind: ClusterConfiguration
kubernetesVersion: v1.17.0
apiServer:
  certSANs:
    - ""
  extraArgs:
    enable-aggregator-routing: "true"
    etcd-servers: ""
controlPlaneEndpoint: ""
#imageRepository: registry-bj.capitalonline.net/cck
imageRepository: capitalonline
networking:
  podSubnet: "10.244.0.0/16"
controllerManagerExtraArgs:
  cloud-provider: external
  allocate-node-cidrs: "true"
controllerManager:
  extraArgs:
    node-cidr-mask-size: "25"
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
mode: ipvs
