apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  labels:
    alertmanager: main
  name: main
  namespace: monitoring
spec:
  tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    effect: "NoSchedule"
  - effect: NoSchedule
    key: node-role.cck.net/infra
  #baseImage: registry-bj.capitalonline.net/cck/prometheus/alertmanager
  baseImage: capitalonline/alertmanager
  nodeSelector:
    kubernetes.io/os: linux
    node-role.kubernetes.io/control-plane:
    node-role.kubernetes.io/infra: ""
  replicas: 3
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: alertmanager-main
  version: v0.18.0
